python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_12_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/12_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/12_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/12_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/12_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/12/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_12_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/12_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/12_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/12_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/12_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/12/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_12_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/12_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/12_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/12_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/12_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/12/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_10_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/10_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/10_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/10_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/10_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/10/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_10_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/10_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/10_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/10_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/10_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/10/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_10_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/10_Neuron_hg19_bestmap.bam -bam2 /dlpfc/bam/10_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/10_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/10_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/10/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_4_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/4_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/4_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/4_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/4_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/4/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_4_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/4_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/4_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/4_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/4_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/4/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_4_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/4_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/4_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/4_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/4_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/4/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_19_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/19_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/19_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/19_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/19_Glia_Input2_hg19_bestmap.bam -bam3 /dlpfc/bam/19_2nd_Glia_H3K27ac1_hg19_bestmap.bam -bam4 /dlpfc/bam/19_2nd_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam3 /dlpfc/bam/19_2nd_Glia_Input1_hg19_bestmap.bam -ctl_bam4 /dlpfc/bam/19_2nd_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/19/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_19_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/19_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/19_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/19_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/19_Microglia_Input2_hg19_bestmap.bam -bam3 /dlpfc/bam/19_2nd_Microglia_H3K27ac1_2_hg19_bestmap.bam -ctl_bam3 /dlpfc/bam/19_2nd_Microglia_Input1_hg19_bestmap.bam -ctl_bam4 /dlpfc/bam/19_2nd_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/19/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_19_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/19_Neuron_hg19_bestmap.bam -bam2 /dlpfc/bam/19_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/19_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/19_Neuron_Input2_hg19_bestmap.bam -bam3 /dlpfc/bam/19_2nd_Neuron_H3K27ac1_hg19_bestmap.bam -bam4 /dlpfc/bam/19_2nd_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam3 /dlpfc/bam/19_2nd_Neuron_Input1_hg19_bestmap.bam -ctl_bam4 /dlpfc/bam/19_2nd_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/19/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_17_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/17_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/17_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/17_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/17_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/17/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_17_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/17_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/17_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/17_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/17_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/17/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_17_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/17_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/17_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/17_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/17_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/17/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_1_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/1_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/1_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/1_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/1_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/1/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_1_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/1_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/1_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/1_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/1_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/1/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_1_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/1_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/1_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/1_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/1_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/1/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_3_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/3_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/3_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/3_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/3_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/3/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_3_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/3_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/3_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/3_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/3_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/3/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_3_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/3_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/3_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/3_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/3_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/3/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_18_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/18_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/18_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/18_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/18_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/18/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_18_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/18_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/18_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/18_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/18_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/18/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_18_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/18_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/18_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/18_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/18_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/18/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_16_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/16_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/16_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/16_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/16_Glia_Input2_bestmap.bam -out_dir /dlpfc/peaks/cases/16/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_16_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/16_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/16_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/16_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/16_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/16/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_16_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/16_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/16_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/16_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/16_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/cases/16/Neuron
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_5_Glia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/5_Glia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/5_Glia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/5_Glia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/5_Glia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/5/Glia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_5_Microglia -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/5_Microglia_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/5_Microglia_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/5_Microglia_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/5_Microglia_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/5/Microglia
python /chipseq_pipeline/chipseq.py -type histone -final_stage idr -title dlpfc_5_Neuron -species hg19 -nth 1 -no_jsd -bam1 /dlpfc/bam/5_Neuron_H3K27ac1_hg19_bestmap.bam -bam2 /dlpfc/bam/5_Neuron_H3K27ac2_hg19_bestmap.bam -ctl_bam1 /dlpfc/bam/5_Neuron_Input1_hg19_bestmap.bam -ctl_bam2 /dlpfc/bam/5_Neuron_Input2_hg19_bestmap.bam -out_dir /dlpfc/peaks/controls/5/Neuron