python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/exPFC1_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC1_markers.txt 5000
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/exPFC2_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC2_markers.txt 5000
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/exCA1_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA1_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/exCA3_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA3_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/GABA1_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA1_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/GABA2_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA2_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/exDG_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exDG_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/ASC1_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC1_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/ASC2_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC2_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/ODC1_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC1_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/ODC2_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC2_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/OPC_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_OPC_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/MG_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_MG_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/NSC_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_NSC_markers.txt 5000 
python get_peaks_matching_gene_ids.py dlpfc_hpc_combined_set_combined_200_name_gene_annot_disttss_gene_name_column.txt /habib_marker_sets/END_markers.txt /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_END_markers.txt 5000 


# both brain regions results
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC1_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC2_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA1_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA3_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA3_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA1_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA2_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exDG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exDG_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC1_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC2_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC1_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC2_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_OPC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_OPC_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_MG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_MG_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_NSC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_NSC_microglia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_END_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_END_microglia_l2fc.txt


grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC1_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC2_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA1_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA3_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA3_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA1_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA2_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exDG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exDG_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC1_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC2_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC1_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC2_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_OPC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_OPC_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_MG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_MG_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_NSC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_NSC_glia_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_END_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_END_glia_l2fc.txt


grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC1_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exPFC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt  | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exPFC2_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA1_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exCA3_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exCA3_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA1_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_GABA2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_GABA2_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_exDG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_exDG_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC1_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ASC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ASC2_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC1_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC1_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_ODC2_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_ODC2_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_OPC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_OPC_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_MG_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_MG_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_NSC_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_NSC_neuron_l2fc.txt
grep -f /habib_markers_analysis_disttss_filter/dlpfc_hpc_peaks_corresponding_to_habib_END_markers.txt /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron_results_sorted.txt | awk -vFS='\t' -vOFS='\t' '{print $3}' > /habib_markers_analysis_disttss_filter/allbr_END_neuron_l2fc.txt
