# cell type term to identify cell type-specific hyperacetylated peaks
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d cell_type -v cell_typeMicroglia -o /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia > /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_microglia.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d cell_type -v cell_typeGlia -o /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia > /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_glia.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d cell_type -v cell_typeNeuron -o /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron > /deseq_analysis/cell_type_deseq/allbr_cell_type_effect_for_neuron.log

# sex 0 (female) specific amyloid beta term

Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c m -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_all_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_all_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c g -o /deseq_analysis/sex_specific_amyloid_deseq/glia_all_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_all_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c n -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_all_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_all_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c nn -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_all_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_all_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -o /deseq_analysis/sex_specific_amyloid_deseq/allct_all_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_all_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c m -b h -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_hpc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_hpc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c g  -b h -o /deseq_analysis/sex_specific_amyloid_deseq/glia_hpc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_hpc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c n  -b h -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_hpc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_hpc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c nn -b h -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_hpc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_hpc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -b h -o /deseq_analysis/sex_specific_amyloid_deseq/allct_hpc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_hpc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c m -b d -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_dlpfc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_dlpfc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c g -b d -o /deseq_analysis/sex_specific_amyloid_deseq/glia_dlpfc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_dlpfc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c n -b d -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_dlpfc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_dlpfc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -c nn -b d -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_dlpfc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_dlpfc_sex_0_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 0 -b d -o /deseq_analysis/sex_specific_amyloid_deseq/allct_dlpfc_sex_0_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_dlpfc_sex_0_specific_binary_amyloid.log

# sex 1 (male) stratified amyloid beta term

Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c m -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_all_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_all_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c g -o /deseq_analysis/sex_specific_amyloid_deseq/glia_all_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_all_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c n -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_all_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_all_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c nn -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_all_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_all_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -o /deseq_analysis/sex_specific_amyloid_deseq/allct_all_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_all_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c m -b h -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_hpc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_hpc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c g  -b h -o /deseq_analysis/sex_specific_amyloid_deseq/glia_hpc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_hpc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c n  -b h -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_hpc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_hpc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c nn -b h -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_hpc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_hpc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -b h -o /deseq_analysis/sex_specific_amyloid_deseq/allct_hpc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_hpc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c m -b d -o /deseq_analysis/sex_specific_amyloid_deseq/microglia_dlpfc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/microglia_dlpfc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c g -b d -o /deseq_analysis/sex_specific_amyloid_deseq/glia_dlpfc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/glia_dlpfc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c n -b d -o /deseq_analysis/sex_specific_amyloid_deseq/neuron_dlpfc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/neuron_dlpfc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -c nn -b d -o /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_dlpfc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/non_neuron_dlpfc_sex_1_specific_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -s 1 -b d -o /deseq_analysis/sex_specific_amyloid_deseq/allct_dlpfc_sex_1_specific_binary_amyloid > /deseq_analysis/sex_specific_amyloid_deseq/allct_dlpfc_sex_1_specific_binary_amyloid.log

# amyloid term

Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c m -o /deseq_analysis/binary_amyloid_deseq/microglia_all_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/microglia_all_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c g -o /deseq_analysis/binary_amyloid_deseq/glia_all_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/glia_all_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c n -o /deseq_analysis/binary_amyloid_deseq/neuron_all_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/neuron_all_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c nn -o /deseq_analysis/binary_amyloid_deseq/non_neuron_all_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/non_neuron_all_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -o /deseq_analysis/binary_amyloid_deseq/allct_all_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/allct_all_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c m -b h -o /deseq_analysis/binary_amyloid_deseq/microglia_hpc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/microglia_hpc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c g  -b h -o /deseq_analysis/binary_amyloid_deseq/glia_hpc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/glia_hpc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c n  -b h -o /deseq_analysis/binary_amyloid_deseq/neuron_hpc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/neuron_hpc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c nn -b h -o /deseq_analysis/binary_amyloid_deseq/non_neuron_hpc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/non_neuron_hpc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -b h -o /deseq_analysis/binary_amyloid_deseq/allct_hpc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/allct_hpc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c m -b d -o /deseq_analysis/binary_amyloid_deseq/microglia_dlpfc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/microglia_dlpfc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c g -b d -o /deseq_analysis/binary_amyloid_deseq/glia_dlpfc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/glia_dlpfc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c n -b d -o /deseq_analysis/binary_amyloid_deseq/neuron_dlpfc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/neuron_dlpfc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -c nn -b d -o /deseq_analysis/binary_amyloid_deseq/non_neuron_dlpfc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/non_neuron_dlpfc_binary_amyloid.log
Rscript run_deseq_all_samples.R -m /counts/all_samples.countSimp.no_header.txt -i all_samples_extended_info.txt -p dlpfc_hpc_combined_set_combined_200_name.saf -d "binary_amyloid" -v binary_amyloid -u 1 -l 0 -b d -o /deseq_analysis/binary_amyloid_deseq/allct_dlpfc_binary_amyloid > /deseq_analysis/binary_amyloid_deseq/allct_dlpfc_binary_amyloid.log
